# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_auto_20160522_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
